"""Build inputs for actual Codex calls. Never authors skill outputs or verdicts."""
import argparse
import json
from pathlib import Path
import shutil
import sys
import yaml

SOURCE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SOURCE / '.game-studio/runtime'))
from installer import install


def put(root, relative, text):
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='\n')


def build(destination):
    root = destination.resolve()
    if root.exists():
        raise ValueError('Use a fresh fixture destination; existing evidence is never reset')
    root.mkdir(parents=True)
    python = str(SOURCE / '.venv/Scripts/python.exe')
    config = {'schema_version': 1, 'project': {'name': 'Native nongame interface fixture', 'stage': 'Production'},
              'modes': {'rigor': 'minimal', 'automation': 'autonomous'}, 'code_root': 'src', 'test_root': 'tests',
              'commands': {'test': [python, '-m', 'unittest', 'discover', '-s', 'tests', '-v'],
                           'build': [python, '-m', 'zipfile', '-c', 'delivery.zip', 'src/counter.py']}}
    put(root, 'project.yaml', yaml.safe_dump(config, sort_keys=False))
    put(root, 'AGENTS.md', f'''# Fixture consumer instructions

This is an isolated nongame interface fixture. Input documents are synthetic;
do not claim game design, engine execution, performance, certification or release
readiness from them. Current human authorization covers requested local reports,
linked JSON receipts, fixture changes and conditional story closure after real
criteria/test/parent review checks. No external publication or engine install.
No delegation is authorized in this fixture; apply professional roles in the parent
and label each result accordingly, never as independent sign-off.
Inherited native permissions/model settings govern the session. Do not modify global
settings, trust hooks, bypass rules or access private game folders. Python with
PyYAML is available at {python}; use it for the installed native helper commands.
''')
    install(SOURCE, root)
    put(root, 'design/game-brief.md', '''# Counter utility fixture brief
Synthetic nongame input. Goal: increment an integer by one with an inclusive cap.
MVP: pure function; increment below limit, clamp at limit and reject bad types/ranges.
Build order: implement, test boundaries, package source. No game/player/engine outcomes.
''')
    put(root, 'production/epics/counter/story-001.md', '''# Pure counter function
**Status:** In Review
Type: Logic
GDD: N/A — minimal fixture brief
ADR Governing Implementation: N/A — pure nongame function
Risk: LOW
## Acceptance Criteria
- increment(2, 5) returns 3.
- increment(5, 5) returns 5; increment(0, 0) returns 0.
- Negative/over-cap integers raise ValueError; boolean/non-integer inputs raise TypeError.
## Implementation
src/counter.py; tests/test_counter.py. No verdict or execution evidence is prefilled.
''')
    for folder, name in [('src', 'counter.py'), ('tests', 'test_counter.py')]:
        (root / folder).mkdir(parents=True, exist_ok=True)
        shutil.copyfile(SOURCE / 'fixtures/minimal-counter' / name, root / folder / name)
    put(root, '.game-studio/context.json', json.dumps({'checkpoint': 'notes/current.md', 'records': []}))
    put(root, 'inputs/provenance.md', 'All brief/story/source/test inputs copied or authored by the fixture builder, not generated by a skill. Output reports/receipts must be produced by actual Codex execution.\n')
    return {'fixture': str(root), 'python': python, 'kind': 'synthetic inputs only'}


def review_inputs(root):
    """Add only synthetic input data for current-session review/ADR/gate exercises."""
    config = yaml.safe_load((root / 'project.yaml').read_text(encoding='utf-8'))
    config['modes']['rigor'] = 'standard'
    config['project']['stage'] = 'Technical Setup'
    config['engine'] = {'name': 'Godot', 'version': '4.3', 'reference_root': 'records/toolchain/godot'}
    # These remain nongame Python commands, not Godot test/build evidence.
    put(root, 'project.yaml', yaml.safe_dump(config, sort_keys=False))
    put(root, 'records/toolchain/godot/VERSION.md', '''# Synthetic project reference input
| Field | Value |
|---|---|
| **Engine Version** | Godot 4.3 |
| **Installed at pin time** | NOT DETERMINED — fixture has no verified Godot probe |
| **Last Docs Verified** | NOT VERIFIED — synthetic record for authority resolution only |
''')
    put(root, 'design/gdd/game-concept.md', '# Synthetic utility concept\nA nongame integer counter, no player fantasy or gameplay. Goal: deterministic bounded increments.\n')
    put(root, 'design/gdd/systems-index.md', '# Synthetic systems index\n| System | Status | Dependency |\n|---|---|---|\n| counter | In Review | limits |\n| limits | In Review | none |\n')
    put(root, 'design/registry/entities.yaml', 'entities: []\n')
    put(root, 'design/gdd/counter.md', '''# Counter utility — synthetic GDD-shaped input
## Summary
Pure bounded integer operation for interface tests; not a game design claim.
## Overview
Increment value by exactly one and clamp to an inclusive limit.
## Player Fantasy
N/A — nongame fixture; no evidence of game experience.
## Detailed Rules
Accept integer value and limit with 0 <= value <= limit. Reject booleans/non-int
with TypeError and invalid integer ranges with ValueError. Shared limits supports
maximum 5; counter examples use cap 5. No IO, engine calls or mutable state.
## Formulas
result = min(value + 1, limit).
## Edge Cases
Zero cap gives zero. At cap returns cap. Negative or over-cap integer rejects.
## Dependencies
- limits.md provides the configured maximum 5.
## Tuning Knobs
limit: caller parameter, range 0..5. No engine/global default.
## Acceptance Criteria
- TR-counter-001: increment(2, 5) returns 3.
- TR-counter-002: increment(5, 5) returns 5; increment(0, 0) returns 0.
- TR-counter-003: invalid type and range inputs raise the stated exception type.
''')
    put(root, 'design/gdd/limits.md', '''# Limits — synthetic GDD-shaped input
## Summary
Shared integer maximum for counter utility inputs.
## Overview
Defines the allowed inclusive maximum as 5.
## Player Fantasy
N/A — nongame fixture.
## Detailed Rules
Configured maximum is 5. Callers may choose lower nonnegative integer limits.
## Formulas
0 <= limit <= maximum; maximum = 5.
## Edge Cases
Zero is valid; boolean/string values are not integers for this contract.
## Dependencies
None
## Tuning Knobs
maximum = 5, intentionally one shared source.
## Acceptance Criteria
- TR-limits-001: chosen limit stays in 0..5; invalid choices are rejected by the caller.
''')
    return {'fixture': str(root), 'added': 'Synthetic GDDs/config/reference inputs only; no review/ADR/gate outputs'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('destination', type=Path)
    parser.add_argument('--review-inputs', action='store_true')
    args = parser.parse_args()
    print(json.dumps(review_inputs(args.destination.resolve()) if args.review_inputs else build(args.destination), indent=2))
